routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Webpage routes
Route::get('/', 'JournalistController@index')->name('journalist-list');
Route::post('journalist/{journalist}/vote/', 'VotingController@vote')->name('journalist-vote');

// Admin routes
Route::prefix('admin')
    ->name('admin.')
    ->namespace('Admin')
    ->middleware('auth')
    ->group(function () {
        Route::resource('settings', 'SettingsController', ['only' => ['index', 'update']]);
        Route::resource('vote', 'VoteController', ['only' => ['destroy']]);
        Route::resource('journalist', 'JournalistController');

        Route::get('journalist/{journalist}/votes', 'JournalistVoteController@index')
            ->name('journalist.votes');

        Route::get('/', function(){
            return view('admin/admin-main');
        })->name('main');

        Route::get('/charts/bar-chart', 'BarChartController@show')
            ->name('bar-chart');
        Route::post('/charts/bar-chart', 'BarChartController@data')
            ->name('bar-chart-data');
});

// Auth routes
Route::namespace('Auth')->group(function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::namespace('Auth')
    ->prefix('password')
    ->name('password.')
    ->group(function () {
        Route::get('reset', 'ForgotPasswordController@showLinkRequestForm')->name('request');
        Route::post('email', 'ForgotPasswordController@sendResetLinkEmail')->name('email');

        Route::get('reset/{token}', 'ResetPasswordController@showResetForm')->name('reset');
        Route::post('reset', 'ResetPasswordController@reset')->name('update');
});

resources/views/admin/admin-main.blade.php
@extends('admin/layout')

@section('title')
    Admin
@endsection

@section('content')
<section class="content">
    <div class="small-box bg-aqua">
        <div class="inner">
            <h1>Welcome to admin panel</h1>
        </div>
    </div>
</section>
@endsection

resources/views/admin/header.blade.php
<header class="main-header">

    <!-- Logo -->
    <a href="#" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>Ad.</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Admin</b></span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top">

      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <!-- Navbar Right Menu -->

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
            <li>
                <form id="logout-form" action="http://localhost:8000/logout" method="POST" style="display: none;">
                    @csrf
                </form>
            </li>
            <li>
                <a href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();" class="dropdown-item">
                    <i class="fa fa-sign-out fa-2x"></i>
                </a>
            </li>
        </ul>
    </nav>
  </header>

resources/views/admin/layout.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>
        @yield('title', 'Admin panel')
    </title>

    <link rel="stylesheet" href="{{ asset('/css/app.css') }}">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    @yield('styles')
</head>
<body class="skin-blue sidebar-mini" style="height: auto; min-height: 100%;">
<div class="wrapper" style="height: auto; min-height: 100%;">

    <div class="wrapper">
        @include('admin/header')
        @include('admin/navbar')

        <div class="content-wrapper" style="min-height: 901px;">
            @yield('content')
        </div>
    </div>

</div>

<script src="{{ asset('/js/app.js') }}" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.js" type="text/javascript"></script>
@yield('scripts')

</body>
</html>

resources/views/admin/navbar.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar" style="height: auto;">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <i class="fa fa-circle-o text-green"></i>
        </div>
        <div class="pull-left info">
          <p>{{ Auth::user()->name }}</p>
        </div>
      </div>
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu tree" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>
        <li class="active treeview">
          <a href="#">
            <i class="fa fa-dashboard"></i> <span>Charts</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu" style="display: none;">
            <li><a href="{{ route('admin.bar-chart') }}"><i class="fa fa-circle-o"></i> Ranking</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-files-o"></i>
            <span>Journalists</span>
          </a>
          <ul class="treeview-menu">
              <li>
                  <a href="{{ route( 'admin.journalist.index' ) }}"><i class="fa fa-circle-o"></i>List</a>
              </li>
              <li>
                  <a href="{{ route( 'admin.journalist.create' ) }}"><i class="fa fa-circle-o"></i>Create</a>
              </li>
          </ul>
        </li>
        <li class="header">Application</li>
        <li>
            <a href="{{ route( 'admin.settings.index' ) }}"><i class="fa fa-circle-o text-aqua"></i><span>Settings</span></a>
        </li>
  </ul>
    </section>
    <!-- /.sidebar -->
  </aside>