routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Webpage routes
Route::get('/', 'JournalistController@index')->name('journalist-list');
Route::post('journalist/{journalist}/vote/', 'VotingController@vote')->name('journalist-vote');

// Admin routes
Route::prefix('admin')
    ->name('admin.')
    ->namespace('Admin')
    ->middleware('auth')
    ->group(function () {
        Route::resource('settings', 'SettingsController', ['only' => ['index', 'update']]);
        Route::resource('vote', 'VoteController', ['only' => ['destroy']]);
        Route::resource('journalist', 'JournalistController');

        Route::get('journalist/{journalist}/votes', 'JournalistVoteController@index')
            ->name('journalist.votes');

        Route::get('/', function(){
            return view('admin/admin-main');
        })->name('main');

        Route::get('/charts/bar-chart', 'BarChartController@show')
            ->name('bar-chart');
        Route::post('/charts/bar-chart', 'BarChartController@data')
            ->name('bar-chart-data');
});

// Auth routes
Route::namespace('Auth')->group(function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::namespace('Auth')
    ->prefix('password')
    ->name('password.')
    ->group(function () {
        Route::get('reset', 'ForgotPasswordController@showLinkRequestForm')->name('request');
        Route::post('email', 'ForgotPasswordController@sendResetLinkEmail')->name('email');

        Route::get('reset/{token}', 'ResetPasswordController@showResetForm')->name('reset');
        Route::post('reset', 'ResetPasswordController@reset')->name('update');
});

app/Settings.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Settings extends Model
{
    protected $table = 'settings';
    protected $fillable = [
        'key',
        'value'
    ];

    public function getRouteKeyName()
    {
        return 'key';
    }
}

app/Http/Controllers/Admin/SettingsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\SettingsRequest;
use App\Http\Controllers\Controller;
use App\Services\SettingsService;
use App\Settings;

class SettingsController extends Controller
{

    public function index(SettingsService $service)
    {
        return view('admin.settings.index',
            [ 'settings' => $service->get_all() ]
        );
    }

    public function update(SettingsRequest $request, SettingsService $service)
    {
        $settings = Settings::firstOrNew(['key' => $request->setting]);
        $settings->value = $request->value;
        $settings->save();

        return view('admin.settings.index',
            ['settings' => $service->get_all()]
        );
    }
}

resources/views/admin/settings/index.blade.php
@extends('admin/layout')

@section('title')
    Settings
@endsection


@section('content')
<section class="content">
    <div class="row">
        @if (isset($message))
        <div class="col-md-6">
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-check"></i> Success! Settings saved</h4>
            </div>
        </div>
        @endif
    </div>
    <div class="row">

        <div class="col-md-6">
            <div class="box box-success">
                <div class="box-header with-border">
                    <h3 class="box-title">Custom settings</h3>
                </div>
                <div class="box-body">
                    @foreach($settings as $key => $value)
                    <form class="" action="{{ route('admin.settings.update', ['setting' => $key ], False)  }}" method="post">
                        @method('PUT')
                        @csrf
                        <div class="form-group  {{ $errors->$key->has('value') ? 'has-error' : '' }}">
                            <label for="first_name">max_votes</label>
                            <input type="text" name="value" class="form-control" value="{{ $value}}">
                            <span class="help-block">{{ $errors->$key->first('value') }}</span>
                        </div>
                        <input type="submit" name="" value="Save" class="btn btn-success">
                    </form>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</section>

@endsection