routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Webpage routes
Route::get('/', 'JournalistController@index')->name('journalist-list');
Route::post('journalist/{journalist}/vote/', 'VotingController@vote')->name('journalist-vote');

// Admin routes
Route::prefix('admin')
    ->name('admin.')
    ->namespace('Admin')
    ->middleware('auth')
    ->group(function () {
        Route::resource('settings', 'SettingsController', ['only' => ['index', 'update']]);
        Route::resource('vote', 'VoteController', ['only' => ['destroy']]);
        Route::resource('journalist', 'JournalistController');

        Route::get('journalist/{journalist}/votes', 'JournalistVoteController@index')
            ->name('journalist.votes');

        Route::get('/', function(){
            return view('admin/admin-main');
        })->name('main');

        Route::get('/charts/bar-chart', 'BarChartController@show')
            ->name('bar-chart');
        Route::post('/charts/bar-chart', 'BarChartController@data')
            ->name('bar-chart-data');
});

// Auth routes
Route::namespace('Auth')->group(function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::namespace('Auth')
    ->prefix('password')
    ->name('password.')
    ->group(function () {
        Route::get('reset', 'ForgotPasswordController@showLinkRequestForm')->name('request');
        Route::post('email', 'ForgotPasswordController@sendResetLinkEmail')->name('email');

        Route::get('reset/{token}', 'ResetPasswordController@showResetForm')->name('reset');
        Route::post('reset', 'ResetPasswordController@reset')->name('update');
});

app/Journalist.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Journalist extends Model
{
    protected $table = 'journalist';
    protected $fillable = [
        'first_name',
        'second_name',
        'image',
        'description',
        'slug',
    ];

    public function save(array $options = [])
    {
        if ($this->slug == null)
        {
            $this->slug = str_slug(
                implode(' ',[$this->first_name, $this->second_name])
            );
        }
        return parent::save($options);
    }

    public function votes()
    {
        return $this->hasMany('App\Vote');
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function fullName()
    {
        return $this->first_name.' '.$this->second_name;
    }
}

app/Http/Controllers/Admin/JournalistController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Journalist;
use App\Http\Requests\JournalistRequest;
use App\Http\Controllers\Controller;

class JournalistController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.journalist.index', [
            'journalist_list' => Journalist::with('votes')->paginate(10)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.journalist.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\JournalistRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(JournalistRequest $request)
    {
        $journalist = Journalist::create(
                $request->only(['first_name', 'second_name','description'])
                + ['image' => $this->processImage($request)]
        );
        $journalist->save();

        return redirect()->route('admin.journalist.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Journalist  $journalist
     * @return \Illuminate\Http\Response
     */
    public function show(Journalist $journalist)
    {
        return view('admin.journalist.show', compact('journalist'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Journalist  $journalist
     * @return \Illuminate\Http\Response
     */
    public function edit(Journalist $journalist)
    {
        return view('admin/journalist/update', compact('journalist'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Journalist  $journalist
     * @return \Illuminate\Http\Response
     */
    public function update(JournalistRequest $request, Journalist $journalist)
    {
        $journalist->update(array_merge(
            $request->only(['first_name', 'second_name','description'])
            + ['image' => $this->processImage($request)]
        ));
        $journalist->save();
        return redirect()
            ->route('admin.journalist.show', ['journalist' => $journalist->slug]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Journalist  $journalist
     * @return \Illuminate\Http\Response
     */
    public function destroy(Journalist $journalist)
    {
        $journalist->delete();
        return redirect()->route('admin.journalist.index');
    }

    /**
     * Process the submitted image
     *
     * @param  \Illuminate\Http\Request  $request
     * @return string $image_name
     */

    private function processImage($request)
    {
        if($request->file('image') != null) {
            $image_name = implode(
                    '.',
                    [
                        $request->first_name,
                        $request->second_name,
                        $request->file('image')->getClientOriginalExtension()
                    ]
                );
            $request->file('image')->move('images', $image_name);
        } else {
            $image_name = 'default.png';
        }
        return $image_name;
    }
}

app/Http/Controllers/JournalistController.php
<?php

namespace App\Http\Controllers;

use App\Journalist;


class JournalistController extends Controller
{
    public function index()
    {
        return view('webpage.journalist.index',
            ['journalist_list' => Journalist::with('votes')->paginate(10)]);
    }
}

resources/views/admin/journalist/_form.blade.php
<div class="box-body">
    <div class="form-group {{ $errors->has('first_name') ? 'has-error' : '' }}">
        <label for="first_name">Name</label>
        <input type="text" name="first_name" class="form-control" value="{{ isset($journalist) ? $journalist->first_name : old('first_name') }}">
        @if ( $errors->has('first_name') )
            <span class="help-block">{{ $errors->first('first_name') }}</span>
        @endif
    </div>
    <div class="form-group {{ $errors->has('second_name') ? 'has-error' : '' }}">
        <label for="second_name">Surname</label>
        <input type="text" name="second_name" class="form-control invalid" value="{{ isset($journalist) ? $journalist->second_name : old('second_name') }}">
        @if ( $errors->has('second_name') )
            <span class="help-block">{{ $errors->first('second_name') }}</span>
        @endif
    </div>
    <div class="form-group {{ $errors->has('description') ? 'has-error' : '' }}">
        <label for="description">Description</label>
        <input type="textarea" name="description" class="form-control" value="{{ isset($journalist) ? $journalist->description : old('description') }}">
        @if ( $errors->has('description') )
            <span class="help-block">{{ $errors->first('description') }}</span>
        @endif
    </div>

    <div class="form-group {{ $errors->has('image') ? 'has-error' : '' }}">
        <label for="image">Image</label>
        <input type="file" id="image" name="image" value="{{ isset($journalist) ? $journalist->image : old('image') }}">
        @if ( $errors->has('image') )
            <span class="help-block">{{ $errors->first('image') }}</span>
        @endif
    </div>
</div>

resources/views/admin/journalist/create.blade.php
@extends('admin.layout')

@section('content')
<section class="content-header">
    <h3>Create journalist</h3>
</section>
<section class="content">
<div class="row">
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Add journalist</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" action="{{ route('admin.journalist.index', [], false) }}"
                  method="POST" enctype="multipart/form-data">
                @csrf
                @include('admin.journalist._form')
                  <!-- /.box-body -->

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                 </div>
            </form>
        </div>
    </div>
</div>
</section>
@endsection

resources/views/admin/journalist/index.blade.php
@extends('admin.layout')

@section('content')
<section class="content-header">
      <h1>
        Journalist list
        <small>a list of journalists</small>
      </h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Journalist table</h3>
                    <div class="box-tools">
                        <div class="input-group input-group-sm" style="width: 150px;">
                            <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">
                        <div class="input-group-btn">
                            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                        </div>
                        </div>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <tbody>
                            <tr>
                                <th>ID</th>
                                <th>First name</th>
                                <th>Second name</th>
                                <th>Votes</th>
                                <th>Rating</th>
                                <th>Actions</th>
                            </tr>
                            @foreach($journalist_list as $journalist)
                            <tr>
                                <td>{{ $journalist->id }}</td>
                                <td>{{ $journalist->first_name }}</td>
                                <td>{{ $journalist->second_name }}</td>
                                <td>{{ $journalist->votes->count() }}</td>
                                <td>{{ $journalist->votes->average('rating') }}</td>
                                <td>
                                  <a href="{{ route('admin.journalist.show',['journalist' => $journalist->slug] , False) }}">
                                      Details</a> |
                                  <a href="{{ route('admin.journalist.edit',['journalist' => $journalist->slug] , False) }}">
                                      Edit</a> |
                                  <a href="{{ route('admin.journalist.votes',['journalist' => $journalist->slug] , False) }}">
                                      Votes</a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
              <!-- /.box -->
        </div>
        <div class="col-md-12">
            {{ $journalist_list->links() }}
        </div>
    </div>
</section>
@endsection

resources/views/admin/journalist/show.blade.php
@extends('admin.layout')

@section('content')
<section class="content-header">
      <h1>
        Journalist details
      </h1>
</section>
<section class="content">
    <div class="box box-widget widget-user">
        <div class="widget-user-header bg-aqua-active">
            <h3 class="widget-user-username">{{ $journalist->first_name }} {{ $journalist->second_name }}</h3>
            <h5 class="widget-user-desc">{{ $journalist->description }}</h5>
        </div>
        <div class="widget-user-image">
            <img class="img-circle" src="/images/{{ $journalist->image }}" alt="User Avatar">
        </div>
        <div class="box-footer">
            <div class="row">
                <div class="col-sm-6 border-right">
                    <div class="description-block">
                        <h5 class="description-header">{{ $journalist->votes->average('rating') }}</h5>
                        <span class="description-text">vote average</span>
                    </div>
                </div>

                <div class="col-sm-6 border-right">
                    <div class="description-block">
                        <h5 class="description-header">{{ $journalist->votes->count() }}</h5>
                        <span class="description-text">vote count</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</secion>
@endsection

resources/views/admin/journalist/update.blade.php
@extends('admin.layout')

@section('content')
<section class="content-header">
    <h3>Edit journalist</h3>
</section>
<section class="content">
<div class="row">
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Edit {{ $journalist->first_name }} {{ $journalist->second_name }}</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" action="{{ route('admin.journalist.update', ['journalist' => $journalist->slug ], false )}}"
                  method="POST" enctype="multipart/form-data">
                @method('PATCH')
                @csrf
                @include('admin.journalist._form')

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                 </div>
            </form>

        </div>
    </div>
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-danger">
            <div class="box-header with-border">
                <h3 class="box-title">Delete {{ $journalist->first_name }} {{ $journalist->second_name }}</h3>
            </div>
            <form  action="{{ route('admin.journalist.destroy',['journalist' => $journalist->slug] , False) }}"
                method="post">
                @method('DELETE')
                @csrf
                <div class="box-footer">
                    <input type="submit" name="Delete" value="Delete" class="btn btn-danger">
                </div>
            </form>
        </div>
    </div>
</div>
</section>
@endsection