routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Webpage routes
Route::get('/', 'JournalistController@index')->name('journalist-list');
Route::post('journalist/{journalist}/vote/', 'VotingController@vote')->name('journalist-vote');

// Admin routes
Route::prefix('admin')
    ->name('admin.')
    ->namespace('Admin')
    ->middleware('auth')
    ->group(function () {
        Route::resource('settings', 'SettingsController', ['only' => ['index', 'update']]);
        Route::resource('vote', 'VoteController', ['only' => ['destroy']]);
        Route::resource('journalist', 'JournalistController');

        Route::get('journalist/{journalist}/votes', 'JournalistVoteController@index')
            ->name('journalist.votes');

        Route::get('/', function(){
            return view('admin/admin-main');
        })->name('main');

        Route::get('/charts/bar-chart', 'BarChartController@show')
            ->name('bar-chart');
        Route::post('/charts/bar-chart', 'BarChartController@data')
            ->name('bar-chart-data');
});

// Auth routes
Route::namespace('Auth')->group(function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::namespace('Auth')
    ->prefix('password')
    ->name('password.')
    ->group(function () {
        Route::get('reset', 'ForgotPasswordController@showLinkRequestForm')->name('request');
        Route::post('email', 'ForgotPasswordController@sendResetLinkEmail')->name('email');

        Route::get('reset/{token}', 'ResetPasswordController@showResetForm')->name('reset');
        Route::post('reset', 'ResetPasswordController@reset')->name('update');
});

app/Vote.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vote extends Model
{
    protected $table = 'vote';
    protected $fillable = [
        'journalist_id',
        'rating',
        'vote_ip'
    ];

    public function journalist()
    {
        return $this->belongsTo('App\Journalist');
    }

}

app/Http/Controllers/Admin/VoteController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Vote;

class VoteController extends Controller
{
    public function destroy(Request $request, Vote $vote)
    {
        $slug = $vote->journalist->slug;
        $vote->delete();
        return redirect()->route('admin.journalist.votes', ['journalist' => $slug]);
    }
}

resources/views/admin/vote/index.blade.php
@extends('admin.layout')

@section('content')
<section class="content-header">

</section>
<section class="content">
    <div class="row">
        <div class="col-md-6">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Votes for {{ $journalist->first_name }} {{ $journalist->second_name }}</h3>
                    </div>
                <ul class="list-group">
                    @foreach($object_list as $object)
                    <li class="list-group-item">
                        <div class="form-group">
                            <form action="{{ route('admin.vote.destroy', ['id' => $object->id ], False) }}" method="post">
                                @method('DELETE')
                                @csrf
                                <input type="submit" name="delete" value="delete" class="btn btn-danger btn-sm pull-right">
                            </form>
                            {{ $object->vote_ip }} at {{ $object->created_at }}
                        </div>
                    </li>
                    @endforeach
                </ul>
            </div>
        </div>
        <div class="col-md-12">
            {{ $object_list->links() }}
        </div>
    </div>
</section>
@endsection